### ISSUE TITLE
menu project 

### ISSUE THREAD

**Issue by Nourhan721** [john-smilga/javascript-basic-projects#141]
hi I was doing the menu project and everything was going okay until i reached the for each part i wrote the code but nothing happened so i don't know where i went wrong . here's the code:

```
filterBtns.forEach(function (btn){
  btn.addEventListener('click',function(e){
  console.log(e.currentTarget.dataset) 
})
})
```

**Comment by hussainabid7199** [comment]
<button class="filter-btn" data-id="1" data-name="Filter 1" data-category="Category A">Filter 1</button>
<button class="filter-btn" data-id="2" data-name="Filter 2" data-category="Category B">Filter 2</button>
<button class="filter-btn" data-id="3" data-name="Filter 3" data-category="Category A">Filter 3</button>
<button class="filter-btn" data-id="4" data-name="Filter 4" data-category="Category C">Filter 4</button>


<script>
    const filterBtns = document.querySelectorAll('.filter-btn');
  filterBtns.forEach((btn) => {
    btn.addEventListener("click", (e) => {
      console.log(e.currentTarget.dataset);
    });
  });

</script>
