### ISSUE TITLE
Error when extracting the zip file

### ISSUE THREAD

**Issue by olekim** [john-smilga/javascript-basic-projects#28]
Hi there,

I have downloaded the javascript-basic-projects-master.zip file, but when I try uncompressing using winrar, I get the following error:

javascript-basic-projects-master.zip: The archive is corrupt

The file is 16.8mb.
Any pointer will be appreciated.
Thanks for your great work, sir!

**Comment by subhi1608** [comment]
I started this tutorial few days back and the zip file worked fine for me maybe you can try downloading again.

**Comment by olekim** [comment]
Thanks, I'll download it again.

Sincerely,

Simon
