### ISSUE TITLE
Menu project

### ISSUE THREAD

**Issue by RitaCr23** [john-smilga/javascript-basic-projects#53]
Hi there, 

I followed the youtube tutorial and I'm unable to get the same result. 

I tried copying and pasting the final code and it still only gives me the buttons and not the filtered menu with all the information inside the array.

Thanks for the great work teaching, but this time I don't know what's wrong!

**Comment by john-smilga** [comment]
Hello,
Did you try running the code in the final folder directly?

**Comment by RitaCr23** [comment]
Thanks for the quick response! :) 

Yes I did, I copied all the code from the final folder and all I have is 3 items from the menu but no buttons. When I copied the code in the final folder into the code I did following the tutorial, all I'd get would be buttons but no menu.

I also rewatched the tutorial and couldn't find what I'm doing wrong!

**Comment by RitaCr23** [comment]
I decided to rewatch the tutorial once again and redo the code, it's working! :D

I'll try to find what did I do wrong the first time and also compare it with the final code, because I find it weird that I couldn't get the same result when just running the final code.
