### ISSUE TITLE
forth project doesn't work

### ISSUE THREAD

**Issue by akrsnr** [john-smilga/javascript-basic-projects#6]
When I open it with `final` folder, menu items are not apparent.

![gifff](https://user-images.githubusercontent.com/17342831/91642817-f98dea80-ea1d-11ea-9ce2-4b9eaa448292.gif)

https://github.com/john-smilga/javascript-basic-projects/tree/master/4-navbar

**Comment by john-smilga** [comment]
I mean you cannot see the part of the logo as well, so the issue is not the project code but your own settings.
